
OrdererOrgs:

  - Name: Orderer
    Domain: antonio.com
    Specs:
      - Hostname: orderer

PeerOrgs:

  - Name: asturias
    Domain: asturias.antonio.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: brasil
    Domain: brasil.antonio.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: chicago
    Domain: chicago.antonio.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
